### ISSUE TITLE
Dataset and Quickstart

### ISSUE THREAD

**Issue by geoexploring** [W-qp/MultiSenseSeg#3]
@W-qp , Thank you for sharing your work. It's very interesting and has given me a lot of inspiration!

Could you please share the dataset you used for training (e.g., a Google Drive link)? Just a small portion of the dataset would be sufficient.

Additionally, perhaps you could consider referring to OmniSat's [README.md](https://github.com/gastruc/OmniSat) to provide more implementation details for reproducing MultiSenseSeg. This could enhance the impact of your work. My small suggestion, 😄

Thanks

**Comment by W-qp** [comment]
> @W-qp , Thank you for sharing your work. It's very interesting and has given me a lot of inspiration!
> 
> Could you please share the dataset you used for training (e.g., a Google Drive link)? Just a small portion of the dataset would be sufficient.
> 
> Additionally, perhaps you could consider referring to OmniSat's [README.md](https://github.com/gastruc/OmniSat) to provide more implementation details for reproducing MultiSenseSeg. This could enhance the impact of your work. My small suggestion, 😄
> 
> Thanks

Thank you for your interest in our work. These two datasets can be found respectively at "https://pan.baidu.com/s/1SgoM8-_JIMJbXyQ9i7eDtw (Key: lala)" and "http://www.wangkaiwei.org/dataseteg.html". The processed dataset is stored in float format, making it too large to share easily (and I'm also unsure if I can share it due to copyright considerations). You can download the original datasets and use "crop.py" for cropping and "labels_RGB2gray.py" for converting RGB labels to indexed form. IF you have any questions in the pre-processing process, you can continue to ask me.

**Comment by geoexploring** [comment]
@W-qp , Thank you for your kind sharing!
